### ISSUE TITLE
Which branch/tag is stable?

### ISSUE THREAD

**Issue by avkashin** [greenplum-db/diskquota#134]
Hi,

I want to build and use diskquota extension. Could you ask please, which branch/tag is stable and suited to greenplum >= 6.17 OSS. 
Thanks!

**Comment by Sasasu** [comment]
tag 1.0.3 is a stable version.

but this version has some known issues:
- PR #99 fixes a bug in the upgrade process from v1.0.2 to v.1.0.3. if you never do upgrade, you can ignore it
- PR #121 and many mentioned current version has a deadlock, and not fixed yet. if you never do drop diskquota, you can ignore it.
- PR #96 fixed a rare bug that can lead to deadlock and cancel some running queries in GPDB cluster. if your cluster is not very large, you can ignore it.

if you just want to build and test, just use tag 1.0.3.

branch `gpdb` is the next 1.0.4 (or 2.0 something). and we trying to solve some rare bugs and improve the troubleshooting experience.
welcome to try `gpdb` branch.

**Comment by avkashin** [comment]
@Sasasu one more question, please. When you plan to release 1.0.4 (or 2.0 something)?

**Comment by Sasasu** [comment]
> When you plan to release 1.0.4 (or 2.0 something)?

in schedule, will be 2022 Q1 in next or this month, but not guarantee.

**Comment by avkashin** [comment]
Thanks!
