### ISSUE TITLE
string may too big

### ISSUE THREAD

**Issue by RekGRpth** [greenplum-db/diskquota#318]
how about instead of constructing large string in https://github.com/greenplum-db/diskquota/blob/a939bc078f9b041059ecb223504abb816753a3e4/src/quotamodel.c#L1158-L1190 use view and it implementation like pg_stat_activity and pg_stat_get_activity to avoid such errors as
```sql
Cannot enlarge string buffer containing 1073741807 bytes by 20 more bytes.
```
?

**Comment by RekGRpth** [comment]
> maybe we should use `COPY`

how can we use `copy` for deleting?

**Comment by RekGRpth** [comment]
> in your use case, it is the `deleted_table_expr`

yes

**Comment by RekGRpth** [comment]
> why using views can mitigate this issue?

because with view one may execute something like
```sql
delete from diskquota.table_size where (tableid, segid) in ( SELECT * FROM deleted_table_view );
```
where deleted_table_view is view, realized via c-function like pg_stat_activity and pg_stat_get_activity

**Comment by RekGRpth** [comment]
at start diskquota tries to load all table into hash map in ram https://github.com/greenplum-db/diskquota/blob/a939bc078f9b041059ecb223504abb816753a3e4/src/gp_activetable.c#L939
but in out case it fails with error
```csv
"ERROR","XX000","invalid memory alloc request size 1073741824 (context 'SPI TupTable') (mcxt.c:1357)",,,,,"SQL statement ""select tableid, size, segid from diskquota.table_size""",,0,,"mcxt.c",571,
```
but this error is catched by https://github.com/greenplum-db/diskquota/blob/a939bc078f9b041059ecb223504abb816753a3e4/src/quotamodel.c#L796-L845 thus diskquota simply ignores ignores unsuccessful loading and filling hash map and thinks that it contains nothing and forms sql to remove all ids from table, but again exceeds max alloc size
```sql
Cannot enlarge string buffer containing 1073741807 bytes by 20 more bytes.
```

**Comment by RekGRpth** [comment]
instead load all table to ram at once I suggest doing something like in pg_prewarm extension

**Comment by zhrt123** [comment]
```
"ERROR","XX000","invalid memory alloc request size 1073741824 (context 'SPI TupTable') (mcxt.c:1357)",,,,,"SQL statement ""select tableid, size, segid from diskquota.table_size""",,0,,"mcxt.c",571,
```
Can you please tell me the scene of this error? This error will not be raised unless the number of entries exceeds 10^8, and we have not encountered that situation currently.

`diskquota.table_size` is used to avoid scanning all tables during cluster startup. And we're considering just scanning all tables and removing `diskquota.table_size` in diskquota-3.0, so that we do not need to fetch or store table size. To avoid occupying too many resources, we will scan tables in portions. I hope to get your opinion.

**Comment by RekGRpth** [comment]
> Can you please tell me the scene of this error? This error will not be raised unless the number of entries exceeds 10^8, and we have not encountered that situation currently.

this error occures on diskquota 2.0 when
```sql
select count(*) from diskquota.table_size;
118458142
```

**Comment by RekGRpth** [comment]
> I hope to get your opinion.

My opinion: segments should manage quotas instead coordinator

**Comment by zhrt123** [comment]
> > Can you please tell me the scene of this error? This error will not be raised unless the number of entries exceeds 10^8, and we have not encountered that situation currently.
> 
> this error occures on diskquota 2.0 when
> 
> ```sql
> select count(*) from diskquota.table_size;
> 118458142
> ```

How do you insert these entries, by creating 10^8 tables?

**Comment by RekGRpth** [comment]
> How do you insert these entries, by creating 10^8 tables?

it became so big after updating from 1.0 to 2.0

**Comment by zhrt123** [comment]
> > I hope to get your opinion.
> 
> My opinion: segments should manage quotas instead coordinator

The segment just has its own table-size information and does not know the entire table's size and whether the quota limit is exceeded. So we manage the quota config on the coordinator.

**Comment by RekGRpth** [comment]
> The segment just has its own table-size information and does not know the entire table's size and whether the quota limit is exceeded. So we manage the quota config on the coordinator.

I suggest distribute whole quota limit between all segments equally

**Comment by zhrt123** [comment]
> I suggest distribute whole quota limit between all segments equally or by some GUC or even setup limit per segment

Thanks for your advice. We've added a per-segment quota limit in diskquota-2.0, which indicates each segment can not exceed `quota_size * ratio` and the whole size can not exceed `quota_size`. If we just dispatch `quota_size * ratio` to each segment and `quota_size * ratio * segment_number` exceeded `quota_size`, the whole quota limit will be invalid.

**Comment by zhrt123** [comment]
> it became so big after updating from 1.0 to 2.0

we added a per-segment quota in diskquota-2.0. It splits each table's size with segid, so the number of entries is multiplied by segment_number.

**Comment by RekGRpth** [comment]
> It splits each table's size with segid, so the number of entries is multiplied by segment_number.

we have over 500 segments

**Comment by zhrt123** [comment]
> we have over 500 segments

Too many TableSizeEntrys is the problem of diskquota-2.x and we plan to solve this problem in diskquota-3.0.
