### ISSUE TITLE
too frequent refresh

### ISSUE THREAD

**Issue by RekGRpth** [greenplum-db/diskquota#319]
how about instead simply wait latch and continue on any signal occured in https://github.com/greenplum-db/diskquota/blob/a939bc078f9b041059ecb223504abb816753a3e4/src/diskquota.c#L489-L523
to use something like https://github.com/greenplum-db/gpdb/blob/6342af5ead95f274e6affae66f2cebd8e4cd0fc6/src/backend/storage/lmgr/condition_variable.c#L170-L232
to avoid situations when with often signals receiving diskquota may call refresh_disk_quota_model frequently than diskquota_naptime

**Comment by zhrt123** [comment]
Do you mean diskquota should not refresh until receiving a signal, and the gap time between two signals should be larger than diskquota_naptime? But the signal is also required to be sent at regular intervals to keep the data in diskquota latest, isn't it?

**Comment by RekGRpth** [comment]
> Do you mean diskquota should not refresh until receiving a signal, and the gap time between two signals should be larger than diskquota_naptime?

no, I mean something like https://github.com/RekGRpth/pg_task/blob/7262c04e642ec744d4a34ae3942f9188bfe38409/work.c#L959 where work_sleep function called not frequently than current_timeout irrespective if WaitEventSetWaitMy function returns frequently

**Comment by zhrt123** [comment]
Get your point, but in this bgworker, the wait latch function only receives `WL_LATCH_SET | WL_TIMEOUT | WL_POSTMASTER_DEATH`. I think it will be not frequently triggered by signals.

**Comment by RekGRpth** [comment]
> I think it will be not frequently triggered by signals.

config reload signal causes WL_LATCH_SET event for example

**Comment by RekGRpth** [comment]
> Do you have any other example for this scene where the latch will be set several times every minute?

this is only theoretical reasoning, what needs to be checked how much time has actually passed since the previous launch

**Comment by zhrt123** [comment]
OK. From our point of view, the bgworker is too complex, so we want to simplify the process. If the latch is only set occasionally, the original code may be sufficient.
