### ISSUE TITLE
user may load diskquota library without shared memory initialization

### ISSUE THREAD

**Issue by Stolb27** [greenplum-db/diskquota#360]
There are several commits (05da9d4 and 86ff586) in diskquota 2.2.2 that eased restrictions for extension initialization check to make it possible to update extension. But! These changes make it possible to run diskquota queries against uninitialized extension too. That leads to segmentation fault on segments as far as shared structures isn't initialized properly.

For example, let's create a stand with diskquota 2.1 and 2.2 shared libraries

## Steps to reproduce 1:

```
\! gpconfig -c shared_preload_libraries -v diskquota-2.1
\! gpstop -arfq
\c
create extension diskquota version '2.1';
\! gpconfig -c shared_preload_libraries -v ''
\! gpstop -arfq
\c
alter extension diskquota update;
drop extension diskquota;
create extension diskquota version '2.2';
```

## Step to reproduce 2:

```
\! gpconfig -c shared_preload_libraries -v diskquota-2.1
\! gpstop -arfq
\c
create extension diskquota version '2.1';
\! gpconfig -c shared_preload_libraries -v ''
\! gpstop -arfq
\c
alter extension diskquota update;
select diskquota.resume();
```

Expected behavior:

```
ERROR:  [diskquota] booting 2.2.2, but diskquota-2.2 not in shared_preload_libraries. abort. (diskquota.c:224)  (seg0 slice1 127.0.1.1:6002 pid=17043) (diskquota.c:224)
CONTEXT:  SQL statement "SELECT diskquota.diskquota_fetch_table_stat(5, '{794247}'::oid[]) FROM gp_dist_random('gp_id')"
```

**Comment by zhrt123** [comment]
Thanks for your issue. We created a PR for this problem.
