### ISSUE TITLE
Build OS and cmake rpm

### ISSUE THREAD

**Issue by kishenkoilya** [greenplum-db/diskquota#364]
I'm curious, on which operating system are you building? I usually build on centos 7, but couldn't find any cmake 3.20+ prebuilt rpms. Did you find any for centos 7 or you build cmake yourself? Or just use OS that doesn't have such problems?

**Comment by kishenkoilya** [comment]
Also another question: contents of archives in releases also need building?

**Comment by zhrt123** [comment]
You can download the latest cmake from the repo: https://github.com/Kitware/CMake/releases.

**Comment by zhrt123** [comment]
```
Also another question: contents of archives in releases also need building?
```
You can delete the error reporter in CMakeLists.txt, this is used for our release procedure.
