### ISSUE TITLE
Misspelling of words

### ISSUE THREAD

**Issue by JennyJennyChen** [greenplum-db/diskquota#40]
branch: gpdb 
quotamodel.c: line 565
mis-spellings: "reset owenr" 
correct spelling: "reset owner"

**Comment by JennyJennyChen** [comment]
branch: gpdb
quotamodel.c: line 705
mis-spellings: "roel_size_map"
correct spelling: "role_size_map"

**Comment by higuoxing** [comment]
Fixed.
