### ISSUE TITLE
Compile alerts

### ISSUE THREAD

**Issue by JennyJennyChen** [greenplum-db/diskquota#41]
branch: gpdb
diskquota.c: line 391
Inline functions are not declared, resulting in compile-time alerts: "diskquota.c:391:13: warning: no previous prototype for 'isAbnormalLoopTime' [-Wmissing-prototypes]"
![ diskquota_compile_alerts](https://user-images.githubusercontent.com/48546628/58955201-da2df080-87cd-11e9-9687-faed8b68f11d.png)

Should be declared near line 89.

**Comment by higuoxing** [comment]
Close, since this issue has been fixed in 3edbaf305fb2e07ac0ccfab18809321deb78e0de.
