### ISSUE TITLE
about diskquota 

### ISSUE THREAD

**Issue by qieding** [greenplum-db/diskquota#47]
I already compile the patch to pg source  and  install  pg   database ;but  when I  make 
diskquota source ,it has a question:
------------------------------------------
quotamodel.c: In function 'calculate_table_disk_usage':
quotamodel.c:541:21:error:'FormData_pg_class' has no member named 'oid'
relOid=classForm->oid;
make: ***[quotamodel.o] Error 1
----------------------------------------
I hope someone can help me,thanks.

**Comment by meiyifei** [comment]
You can modify the line of error code,like this:
Form_pg_class classForm = (Form_pg_class) GETSTRUCT(tuple);
relOid = classForm->relfilenode;

**Comment by higuoxing** [comment]
Looks this question has already been answered. Close. Feel free to reopen.
