### ISSUE TITLE
cc1: some warnings being treated as errors

### ISSUE THREAD

**Issue by anjingde** [greenplum-db/diskquota#50]
gdb
diskquota.c: In function ‘dq_object_access_hook’:
diskquota.c:1039:20: error: ‘MyProc’ undeclared (first use in this function)
    rc = WaitLatch(&MyProc->procLatch,
                    ^~~~~~
diskquota.c:1041:16: error: ‘PG_WAIT_EXTENSION’ undeclared (first use in this function)
          100L, PG_WAIT_EXTENSION);
                ^~~~~~~~~~~~~~~~~
diskquota.c:1039:9: error: too many arguments to function ‘WaitLatch’
    rc = WaitLatch(&MyProc->procLatch,
rc = WaitLatch(&MyProc->procLatch,
         ^~~~~~~~~
postgresql/server/storage/latch.h:136:12: note: declared here
 extern int WaitLatch(volatile Latch *latch, int wakeEvents, long timeout);
            ^~~~~~~~~
cc1: some warnings being treated as errors
make: *** [diskquota.o] Error 1

how to deal with this problem?

**Comment by anjingde** [comment]
branch gpdb make

**Comment by HaozhouWang** [comment]
Hi, 

Could you please provide the OS version/GPDB version/GCC version to identify the issue?

For PG, please use the master branch, for GPDB (6.1+) please use the gpdb branch

**Comment by anjingde** [comment]
@HaozhouWang Thank you for your answer ,I deal with this problem by using true branch.

**Comment by higuoxing** [comment]
Close, since it's resolved.
